break_into_partial_movies: false
camera_resolutions:
  4k: 3840x2160
  default_resolution: 4k
  high: 1920x1080
  low: 854x480
  medium: 1280x720
directories:
  mirror_module_path: false
  output: outputs
  raster_images: .png
  sounds: .mp3
  temporary_storage: temp
  vector_images: .svg
fps: 30
full_screen: false
style:
  background_color: '#333333'
  font: Euclid
  tex_template: default
universal_import_line: from manimlib import *
window_monitor: 0
window_position: UR
